import { Lawyer, BrandRecord } from "./types";

export const LAWYERS: Lawyer[] = [
  {
    id: "law-1",
    name: "Priya Nair",
    specialization: "Corporate & Contract Lawyer",
    location: "Mumbai, India",
    languages: ["English", "Hindi"],
    fee: "$80 / consultation",
    email: "priya.nair@businesslegal.example",
    rating: 4.9,
    bio: "12 years advising businesses and independent consultants on vendor agreements, service contracts, and IP disputes.",
  },
  {
    id: "law-2",
    name: "Marcus Webb",
    specialization: "IP Lawyer",
    location: "Los Angeles, USA",
    languages: ["English"],
    fee: "$150 / consultation",
    email: "marcus.webb@iplaw.example",
    rating: 4.8,
    bio: "Specializes in intellectual property ownership, software licensing, and copyright disputes for businesses.",
  },
  {
    id: "law-3",
    name: "Elena Rossi",
    specialization: "Contract & Corporate Lawyer",
    location: "Milan, Italy",
    languages: ["English", "Italian", "French"],
    fee: "€95 / consultation",
    email: "elena.rossi@contractlaw.example",
    rating: 4.7,
    bio: "Reviews and redlines service and vendor agreements for SaaS and corporate clients across the EU.",
  },
  {
    id: "law-4",
    name: "David Okafor",
    specialization: "Business Contract Advisor",
    location: "Remote / Global",
    languages: ["English"],
    fee: "$60 / consultation",
    email: "david.okafor@businesslaw.example",
    rating: 4.9,
    bio: "Former corporate counsel, now advising businesses and startups on negotiation strategy and deal structuring.",
  },
  {
    id: "law-5",
    name: "Sofia Martinez",
    specialization: "Corporate & Contract Lawyer",
    location: "Mexico City, Mexico",
    languages: ["English", "Spanish"],
    fee: "$70 / consultation",
    email: "sofia.martinez@businesslegal.example",
    rating: 4.6,
    bio: "Focuses on exclusivity clauses, termination fees, and indemnification rights for business services.",
  },
  {
    id: "law-6",
    name: "James Lindqvist",
    specialization: "IP & Tech Lawyer",
    location: "Stockholm, Sweden",
    languages: ["English", "Swedish"],
    fee: "€110 / consultation",
    email: "james.lindqvist@iplaw.example",
    rating: 4.8,
    bio: "Advises SaaS companies and service providers on software agreements, licensing terms, and corporate partnership agreements.",
  },
];

export const BRAND_RECORDS: BrandRecord[] = [
  {
    name: "Aero Audio",
    riskLevel: "Low",
    avgUsageWindow: "60 days",
    dealsTracked: 34,
    commonIssues: ["Minor payment delays"],
  },
  {
    name: "GlowGrid",
    riskLevel: "Medium",
    avgUsageWindow: "6 months",
    dealsTracked: 21,
    commonIssues: ["Vague payment terms", "Unlimited revisions"],
  },
  {
    name: "Northwave Apparel",
    riskLevel: "Medium",
    avgUsageWindow: "9 months",
    dealsTracked: 18,
    commonIssues: ["Broad exclusivity", "No kill fee"],
  },
  {
    name: "Lumen Beauty",
    riskLevel: "High",
    avgUsageWindow: "Perpetual",
    dealsTracked: 27,
    commonIssues: ["Unlimited usage rights", "Whitelisting without pay", "No kill fee"],
  },
  {
    name: "Vita Wellness",
    riskLevel: "High",
    avgUsageWindow: "Perpetual",
    dealsTracked: 15,
    commonIssues: ["Work-for-hire ownership", "Vague termination", "12-month exclusivity"],
  },
];

export const COMMON_EXPLOITATIVE_CLAUSES = [
  { clause: "Perpetual, worldwide usage rights", frequency: 64 },
  { clause: "Whitelisting without separate compensation", frequency: 52 },
  { clause: "No kill fee on cancellation", frequency: 47 },
  { clause: "Unlimited revision rounds", frequency: 41 },
  { clause: "Vague/subjective termination rights", frequency: 38 },
  { clause: "Work-for-hire content ownership", frequency: 29 },
];
